version: "3"
services: 
  mysql:
    image: mysql:5.6
    restart: on-failure
    ports: 
      - 3306:3306
    volumes: 
      - "/o2o/mysql/data:/var/lib/mysql"
      - "/o2o/mysql/conf:/etc/mysql/conf.d"
      - "/o2o/mysql/logs:/logs"
    environment: 
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: o2o
    deploy: 
      replicas: 1
      restart_policy: 
        condition: on-failure
      placement: 
        constraints: [node.role == manager]
  eureka-server: 
    image: ccr.ccs.tencentyun.com/meimengmeng/weixin-server:0.0.1-SNAPSHOT
    restart: on-failure
    ports: 
      - 8000:8000
    deploy: 
      replicas: 1
      restart_policy: 
        condition: on-failure
  gateway-zuul: 
    image:
    restart: on-failure
    ports: 
      - 8100:8100
    depends_on: 
      - eureka-server
    deploy: 
      replicas: 1
      restart_policy: 
        condition: on-failure
      placement: 
        constraints: [node.role == manager]
  commodity_service: 
    image: ccr.ccs.tencentyun.com/meimengmeng/weixin-commodity:0.0.1-SNAPSHOT
    restart: on-failure
    ports: 
      - 8400:8400
    depends_on:
      - mysql
      - eureka-server
    deploy: 
      replicas: 2
      restart_policy:
        condition: on-failure      
  seller_service: 
    image: ccr.ccs.tencentyun.com/meimengmeng/weixin-seller:0.0.1-SNAPSHOT
    restart: on-failure
    ports: 
      - 8500:8500
    depends_on:
      - mysql
      - eureka-server
    deploy: 
      replicas: 2
      restart_policy:
        condition: on-failure
  order_service: 
    image: ccr.ccs.tencentyun.com/meimengmeng/weixin-order:0.0.1-SNAPSHOT
    restart: on-failure
    ports: 
      - 8200:8200
    depends_on:
      - mysql
      - eureka-server
    deploy: 
      replicas: 2
      restart_policy:
        condition: on-failure
  user_service: 
    image: ccr.ccs.tencentyun.com/meimengmeng/weixin-user:0.0.1-SNAPSHOT
    restart: on-failure
    ports: 
      - 8300:8300
    depends_on:
      - mysql
      - eureka-server
    deploy: 
      replicas: 2
      restart_policy:
        condition: on-failure
  tool_service: 
    image: ccr.ccs.tencentyun.com/meimengmeng/weixin-tool:0.0.1-SNAPSHOT
    restart: on-failure
    ports: 
      - 8600:8600
    depends_on:
      - mysql
      - eureka-server
    deploy: 
      replicas: 2
      restart_policy:
        condition: on-failure