server:
  port: 8600
springfox:
  documentation:
    swagger:
      v2:
        path: /v1/api-docs
spring: 
  profiles:
    include:
    - common
    active:
    - dev
  datasource: 
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      dbcp2:
        max-total: 5
        min-idle: 5
        initial-size: 5
        max-wait-millis: 10000
  application:
    name: tool
  messages:
    basename: i18n/Messages
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.mmm.weixin.vo
  mapper-locations:
  - classpath:mybatis/mapper/*.xml
---
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/o2o?characterEncoding=utf8
#   url: jdbc:mysql://mysql:3306/weixin
    username: root
    password: Afv1998122820120814
  profiles: dev
eureka: 
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
#     服务器地址
#     defaultZone: http://localhost:8000/eureka/ 
logging:
  level:
      com.mmm.weixin.dao: debug
      
rest_template_prefix: http://${shop_service}/
---
spring: 
  datasource:
    url: jdbc:mysql://172.81.252.137:3306/o2o?characterEncoding=utf8
#   url: jdbc:mysql://mysql:3306/weixin
    username: root
    password: uthH8&jDk#
  profiles: prod
eureka:
  client:
    service-url:
      defaultZone: http://172.81.252.137:8000/eureka/
#     服务器地址
#     defaultZone: http://localhost:8000/eureka/ 
rest_template_prefix: http://${shop_service}/
---
province_parentId: 0
websocket_url: https://kf123.cywl168.cn/