server:
  port: 8200
springfox:
  documentation:
    swagger:
      v2:
        path: /v1/api-docs
spring: 
  profiles:
    include:
    - common
    active:
    - dev
  datasource: 
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      dbcp2:
        max-total: 5
        min-idle: 5
        initial-size: 5
        max-wait-millis: 10000
  application:
    name: order
  messages:
    basename: i18n/Messages
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.mmm.weixin.vo
  mapper-locations:
  - classpath:mybatis/mapper/*.xml

---
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/o2o?characterEncoding=utf8
#   url: jdbc:mysql://mysql:3306/weixin
    username: root
    password:
  profiles: dev
eureka: 
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
#     服务器地址
#     defaultZone: http://localhost:8000/eureka/ 
logging:
  level:
      com.mmm.weixin.dao: debug
---
spring: 
  datasource:
    url:
#   url: jdbc:mysql://mysql:3306/weixin
    username: root
    password:
  profiles: prod
eureka: 
  client:
    service-url:
      defaultZone:
#     服务器地址
#     defaultZone: http://localhost:8000/eureka/
---
OrderInfo:
  Body: "尊享管家"
  Create_ip:
  Notifyurl:
  Trade_type: "JSAPI"
  Sign_type: "MD5"
#订单信息